CREATE TABLE IF NOT EXISTS task
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    due_date    timestamp    NOT NULL,
    completed   boolean      NOT NULL
);
